# Lab 2 - Linear Systems as Matrices

### Objective
Learn how to represent linear systems as matrices,
perform matrix operations, and solve linear systems using NumPy.

In [36]:
import numpy as np

### Task 1 - Representing Linear Systems as Matrices

1. Consider the system of equations

    `3x + 4y = 7`<br />
    `2x - y = 1`

    Write the system as a matrix equation `AX = B`, where:
    - A is the coefficient matrix
    - X is the vector of unknowns
    - B is the right-hand side vector
2. Create the matrices using NumPy:
    - $A = \begin{bmatrix} 3 & 4 \\ 2 & -1 \end{bmatrix}$
    - $B = \begin{bmatrix} 7 \\ 1 \end{bmatrix}$

1. $\begin{bmatrix} 3 & 4 \\ 2 & -1 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix} = \begin{bmatrix} 7 \\ 1 \end{bmatrix}$

In [43]:
# 2.
A = np.array([[3, 4], [2, -1]])
B = np.array([[7], [1]])

print('A')
print(A, end="\n\n")

print('B')
print(B)

A
[[ 3  4]
 [ 2 -1]]

B
[[7]
 [1]]


### Questions
1. What is the shape of matrix `A`?
2. How do you interpret the system of equations from the matrix form?

In [41]:
# 1.
print(f'Shape of matrix A: {A.shape}')

Shape of matrix A: (2, 2)


2. Each row of the matrix represents one equation in the system, with the elements in that row corresponding to the coefficients of each variable in the equation, while the column positions represent the variables themselves

### Task 2 - Solving the System

1. Using NumPy, solve for the vector `X` ($x$ and $y$) in the matrix equation $AX = B$

In [42]:
# 1.
solution = np.linalg.solve(A, B)
print(solution, end="\n\n")

[[1.]
 [1.]]



### Questions
1. What are the values of $x$ and $y$?

In [40]:
# 1.
print(f'x = {solution[0]}')
print(f'y = {solution[1]}')

x = [1.]
y = [1.]
