# Lab 1 - Introduction to NumPy Arrays

### Objective
Learn the basics of creating, manipulating, and using NumPy
arrays for linear algebra applications

In [29]:
import numpy as np

### Task 1 - Creating NumPy Arrays

#### Create the following
1. A 1D array with elements `[1, 2, 3, 4, 5]`
2. A 2D array with the shape `(3, 3)` containing integers from `1` to `9`

In [30]:
# 1.
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [31]:
# 2.
arr2 = np.array([x for x in range(1, 10)])
arr2.shape = (3, 3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Questions
1. What is the shape of each array?
2. Can you change the shape of the 1D array into a `(1, 5)` and a `(5, 1)` array?

In [32]:
# 1.
print(f'Shape of 1D array: {arr1.shape}')
print(f'Shape of 2D array: {arr2.shape}')

Shape of 1D array: (5,)
Shape of 2D array: (3, 3)


In [33]:
# 2.
arr1.shape = (1, 5)
print('1D array with a (1, 5) shape')
print(arr1, end='\n\n')

arr1.shape = (5, 1)
print('2D array with a (5, 1) shape:')
print(arr1)

1D array with a (1, 5) shape
[[1 2 3 4 5]]

2D array with a (5, 1) shape:
[[1]
 [2]
 [3]
 [4]
 [5]]


Yes you can change the shape of the 1D array into a `(1, 5)` and `(5, 1)` array!


### Task 2 - Array Operations

1. Create two 1D arrays
2. Perform the following operations:
    1. Element-wise addition
    2. Element-wise multiplication
    3. Dot Product

In [47]:
# 1.
first_arr = np.array([1, 2, 3])
second_arr = np.array([4, 5, 6])

# arr1.shape and arr2.shape should be (3,) indicating a 1D array of 3 elements
print(f'1D Array: {first_arr}. Shape: {first_arr.shape}')
print(f'2D Array: {second_arr}. Shape: {second_arr.shape}')

1D Array: [1 2 3]. Shape: (3,)
2D Array: [4 5 6]. Shape: (3,)


In [48]:
# 2.
arr_sum = np.add(first_arr, second_arr)
product = np.multiply(first_arr, second_arr)
dot_product = np.dot(first_arr, second_arr)

print(f'Element wise addition: {arr_sum}')
print(f'Element wise multiplication: {product}')
print(f'Dot Product: {dot_product}')

Element wise addition: [5 7 9]
Element wise multiplication: [ 4 10 18]
Dot Product: 32


### Questions
1. What is the difference between `np.dot(a, b)` and `a * b`?
2. Can you compute the Euclidean distance between the two arrays?

1. `np.dot(a, b)` calculates the dot product of vectors `a` and `b` (represented as NumPy arrays in Python), while `a * b` calculates the normal product of vectors `a` and `b`

In [53]:
# 2. Euclidean Distance
print(f'Euclidean Distance between {first_arr} and {second_arr}: {np.sqrt(np.sum((first_arr - second_arr) ** 2))}')

Euclidean Distance between [1 2 3] and [4 5 6]: 5.196152422706632


### Task 3 - Matrix Operations

1. Create a 2D array `A` with shape `(2, 2)`
2. Perform the following operations
    1. Transpose the matrix
    2. Compute the determinant
    3. Find the inverse (if it exists)

In [58]:
# 1.
A = np.array([[1, 2], [3, 4]])

print(f'2D Array A with shape (2, 2)')
print(A, end='\n\n')
# Verify shape is (2, 2)
print(f'Shape: {A.shape}')

2D Array A with shape (2, 2)
[[1 2]
 [3 4]]

Shape: (2, 2)


In [62]:
# 2.
A_transpose = np.transpose(A)
det = np.linalg.det(A)
inverse = np.linalg.inv(A)

print('Transpose')
print(A_transpose, end='\n\n')

print(f'Determinant: {det}', end='\n\n')

print(f'Inverse')
print(inverse)

Transpose
[[1 3]
 [2 4]]

Determinant: -2.0000000000000004

Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


### Questions

1. What happens when the determinant is zero?
2. Explain why the matrix might not have an inverse

1. When the determinant is zero, the matrix is singular. This means that its system has a unique solution

In [67]:
# Example matrix that has a determinant of 0
# The products of the diagonals (ad and bc) are equal
mat = np.array([[1, 2], [2, 4]])
det = np.linalg.det(mat)

print(f'Matrix determinant: {det}')

Matrix determinant: 0.0


In [70]:
# THIS CODE ERRORS!

inverse = np.linalg.inv(mat)
print(f'Inverse: {inverse}')

LinAlgError: Singular matrix

2. The code above errors because when a matrix has a determinant of zero, it doesn't have an inverse. This is because the columns of the matrix are linearly dependent (rows depend on each other)

### Task 4 - Slicing and Indexing

1. Create 2D array `B` with contents
    1. `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`
2. Perform the following
    1. Extract the row
    2. Extract the second column
    3. Extract the sub matrix
        1. `[[50, 60], [80, 90]]`

In [71]:
# 1.
B = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print(B)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [80]:
# 2.
row = B[0, :]
second_col = B[:, 1]
sub_mat = B[1:, 1:]

print(f'Row: {row}', end='\n\n')

print(f'Second Column: {second_col}', end='\n\n')

print('Sub-matrix')
print(sub_mat)

Row: [10 20 30]

Second Column: [20 50 80]

Sub-matrix
[[50 60]
 [80 90]]


### Questions

1. What happens if you try to access an index out of bounds?
2. How can you extract diagonal elements from the matrix?

In [81]:
# 1. (THIS CODE WILL ERROR!)

sub_mat_2 = B[3, :]
print(sub_mat_2)

IndexError: index 3 is out of bounds for axis 0 with size 3

1. Attempting to access an index out of bounds will result in an `IndexError`

In [114]:
# 2.
left_diag = np.diag(sub_mat)
left_diag_1 = np.diag(sub_mat, -1)
right_diag = np.diag(np.fliplr(sub_mat))

print(f'Left diagonal: {left_diag}')
print(f'First element below left diagonal: {left_diag_1}')
print(f'Right diagonal: {right_diag}')

Left diagonal: [50 90]
First element below left diagonal: [80]
Right diagonal: [60 80]


2. Extracting diagonal elements can be done by using Numpy's `diag()` function