# Lab 4 - Gaussian Elimination

### Objective
Learn to implement the Gaussian Elimination algorithm using Python and NumPy, which is used to solve a system by transforming its matrix into one that is in row-echelon or reduced row-echelon form.

In [202]:
import numpy as np

## Introduction

### The Gaussian Elimination algorithm involves 3 main steps

1. Convert the system into an augmented matrix
2. Use forward elimination to convert the augmented matrix into row echelon form
3. Use back substitution to solve for variables starting from the last row in the matrix

The code for this algorithm can be split into these 3 main steps

### Task 1 - Augumented Matrix

1. Implement the augmented matrix for the system below

    $\begin{aligned}
    &2x + y - z = 8 \\
    &-3x - y + 2z = -11 \\
    &-2x + y + 2z = -3
    \end{aligned}$

In [203]:
# 1.
A = np.array([[2, 3, -1], [4, 1, 1], [-2, 5, 3]], dtype=float)
B = np.array([[1, 6, 5]], dtype=float)
# A = np.array([[2, 1, -1], [-3, -1, 2], [-2, 1, 2]], dtype=float)
# B = np.array([8, -11, -3], dtype=float)

print(f"A\n{A}\n")
print(f"B\n{B}\n")

augmented_matrix = np.hstack((A, B.reshape(-1, 1)))
print(f'Augmented matrix for A and B')
print(augmented_matrix)

A
[[ 2.  3. -1.]
 [ 4.  1.  1.]
 [-2.  5.  3.]]

B
[[1. 6. 5.]]

Augmented matrix for A and B
[[ 2.  3. -1.  1.]
 [ 4.  1.  1.  6.]
 [-2.  5.  3.  5.]]


### Task 2 - Forward Elimination

1. Using the system and augmented matrix from Task 1, implement the second step of the gaussian elimination algorithm: forward elimination

Recall that Forward elimination involves using row operations to convert an augmented matrix into its row echelon form

In [204]:
# 1.
rows, cols = augmented_matrix.shape
for i in range(rows):
    # Normalize the pivot row
    augmented_matrix[i, :] = augmented_matrix[i, :] / augmented_matrix[i, i]

    # Zero out the columns below the pivot
    for j in range(i + 1, rows):
        scale_factor = augmented_matrix[j, i]
        augmented_matrix[j, :] = augmented_matrix[j, :] - scale_factor * augmented_matrix[i, :]

# The resulting matrix is in row echelon form
print(augmented_matrix)

[[ 1.          1.5        -0.5         0.5       ]
 [-0.          1.         -0.6        -0.8       ]
 [ 0.          0.          1.          1.82352941]]


### Task 3 - Back Substitution

1. Using the augmented matrix thats in row echelon form from Task 2, implement the third step of the gaussian elimination algorithm: back substitution

Recall that Back Subtitution solves for the unknown variables in a matrix by working from the bottom row to the top of a matrix in row echelon form

In [205]:
# 1.
solutions = np.zeros(rows)
for i in range(rows - 1, -1, -1):
    solutions[i] = augmented_matrix[i, -1] - np.dot(augmented_matrix[i, i+1:cols-1], solutions[i+1:])

x, y, z = solutions
print(f'x = {x}')
print(f'y = {y}')
print(f'z = {z}')

x = 0.9705882352941176
y = 0.2941176470588236
z = 1.823529411764706


### Bonus Task - Reduced Row Echelon Form (RREF)

Task 2 involved simplifying a matrix into its row echelon form.

1. However, an additional step can be taken to simplify the row echelon form matrix even further. This involves simplifying the row echelon form matrix into its reduced row echelon form

Recall that in reduced row echelon form, the matrix's elements are also zero past the pivot

In [206]:
# 1.
for i in range(rows):
    # Make the pivot 1
    pivot = augmented_matrix[i, i]
    if pivot != 0:
        augmented_matrix[i, :] = augmented_matrix[i, :] / pivot

    # Zero the elements below the pivot
    for j in range(i + 1, rows):
        factor = augmented_matrix[j, i]
        augmented_matrix[j, :] = augmented_matrix[j, :] - factor * augmented_matrix[i, :]

# Backwards elimination to zero out elements above the pivots
for i in range(rows - 1, -1, -1):
    for j in range(i - 1, -1, -1):
        factor = augmented_matrix[j, i]
        augmented_matrix[j, :] = augmented_matrix[j, :] - factor * augmented_matrix[i, :]

# The result is a reduced row echelon form matrix
print(augmented_matrix)

[[1.         0.         0.         0.97058824]
 [0.         1.         0.         0.29411765]
 [0.         0.         1.         1.82352941]]
